const data = [
  {
    id: 1,
    title: "tag to wear",
    price: 148,
    discount: 20,
    del: 287,
    seller: "by mango",
    category: "men",
    tag: ["trending now"],
    brand: null,
    images: [
      require("../assets/images/products/a.jpg"),
      require("../assets/images/products/a1.webp"),
      require("../assets/images/products/a2.webp"),
      require("../assets/images/products/a3.webp"),
      require("../assets/images/products/a4.webp"),
    ],
    variants: [],
    specification: "",
    features: "",
    product_reviews: [],
    product_code: "460356366_floral",
    product_details:
      "Black, off-white and peach-coloured printed flared skirt, has zip closure, attached lining",
  },
  {
    id: 2,
    title: "Real italian gold",
    price: 200,
    discount: 20,
    del: 287,
    seller: "by mango",
    category: "men",
    tag: ["trending now", "top picks"],
    brand: null,
    images: [
      require("../assets/images/products/b.webp"),
      require("../assets/images/products/b1.webp"),
      require("../assets/images/products/b2.webp"),
      require("../assets/images/products/b3.webp"),
      require("../assets/images/products/b4.webp"),
    ],
    variants: [],
    specification: "",
    features: "",
    product_reviews: [],
    product_code: "460356366_floral",
    product_details:
      "Black, off-white and peach-coloured printed flared skirt, has zip closure, attached lining",
  },
  {
    id: 3,
    title: "Blue Denim Jacket",
    price: 420,
    discount: 20,
    del: 287,
    seller: "by mango",
    category: "men",
    tag: ["top rated", "featured products", "top picks"],
    brand: null,
    images: [
      require("../assets/images/products/c.webp"),
      require("../assets/images/products/c1.webp"),
      require("../assets/images/products/c2.webp"),
      require("../assets/images/products/c3.webp"),
      require("../assets/images/products/c4.webp"),
    ],
    variants: [],
    specification: "",
    features: "",
    product_reviews: [],
    product_code: "460356366_floral",
    product_details:
      "Black, off-white and peach-coloured printed flared skirt, has zip closure, attached lining",
  },
  {
    id: 4,
    title: "tag to wear",
    price: 185,
    discount: 20,
    del: 287,
    seller: "by mango",
    category: "men",
    tag: ["top rated"],
    brand: null,
    images: [require("../assets/images/products/4.jpg")],
    variants: [],
    specification: "",
    features: "",
    product_reviews: [],
    product_code: "460356366_floral",
    product_details:
      "Black, off-white and peach-coloured printed flared skirt, has zip closure, attached lining",
  },
  {
    id: 5,
    title: "Blue Denim Jacket",
    price: 200,
    discount: 20,
    del: 287,
    seller: "by mango",
    category: "men",
    tag: ["trending now"],
    brand: null,
    images: [require("../assets/images/products/5.jpg")],
    variants: [],
    specification: "",
    features: "",
    product_reviews: [],
    product_code: "460356366_floral",
    product_details:
      "Black, off-white and peach-coloured printed flared skirt, has zip closure, attached lining",
  },
];

export default data;
